package sdk

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

const docsManifest = ".karty-docs.json"

const (
	errInvalidDocsPath staticError = "SDK docs contain an invalid path"
	errDocsNotDir      staticError = "SDK reference is not a directory"
	errDocsManifest    staticError = "SDK reference has an invalid generated manifest"
	errDocsSpecial     staticError = "SDK reference entry is not a regular file"
	errDocsModified    staticError = "SDK reference was modified; move user files outside .karty/docs"
	errDocsFileSet     staticError = "SDK reference file set was modified; move user files outside .karty/docs"
)

type docsState struct {
	Warning    string            `json:"warning"`
	DoNotEdit  string            `json:"doNotEdit"`
	Regenerate string            `json:"regenerate"`
	SDK        string            `json:"sdk"`
	Files      map[string]string `json:"files"`
}

// SyncDocs replaces the project-local reference with the exact set selected by
// the SDK. Existing generated files must still match their recorded hashes.
//
//nolint:wsl_v5 // Ordered filesystem writes are clearer as one transactional sequence.
func SyncDocs(projectDirectory string, manifest Manifest) error {
	root := filepath.Join(projectDirectory, ".karty", "docs")
	if err := verifyDocs(root); err != nil {
		return err
	}

	if err := os.RemoveAll(root); err != nil {
		return fmt.Errorf("replace SDK reference: %w", err)
	}

	if manifest.Docs.Version == "" {
		return nil
	}

	files, err := resolveDocs(manifest)
	if err != nil {
		return err
	}

	state := docsState{
		Warning:    "GENERATED BY KARTY. DO NOT EDIT.",
		DoNotEdit:  "MANUAL CHANGES WILL BE REJECTED OR REPLACED.",
		Regenerate: "karty build",
		SDK:        manifest.Version,
		Files:      make(map[string]string, len(files)),
	}

	for name, contents := range files {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
			return fmt.Errorf("create SDK reference directory: %w", err)
		}
		if err := os.WriteFile(path, contents, 0o600); err != nil {
			return fmt.Errorf("write SDK reference %s: %w", name, err)
		}
		state.Files[name] = digest(contents)
	}

	encoded, err := json.MarshalIndent(state, "", "  ")
	if err != nil {
		return fmt.Errorf("encode SDK reference manifest: %w", err)
	}
	encoded = append(encoded, '\n')
	if err := os.WriteFile(filepath.Join(root, docsManifest), encoded, 0o600); err != nil {
		return fmt.Errorf("write SDK reference manifest: %w", err)
	}

	return nil
}

//nolint:wsl_v5,nlreturn // The embedded-tree walk is intentionally kept together.
func resolveDocs(manifest Manifest) (map[string][]byte, error) {
	tree, err := Resources(manifest)
	if err != nil {
		return nil, err
	}
	prefix := "docs/" + manifest.Docs.Version
	result := make(map[string][]byte)
	err = fs.WalkDir(tree, prefix, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}
		contents, err := fs.ReadFile(tree, path)
		if err != nil {
			return err
		}
		name := strings.TrimPrefix(path, prefix+"/")
		if name == path || name == "" || !fs.ValidPath(name) {
			return fmt.Errorf("SDK docs %s path %q: %w", manifest.Docs.Version, path, errInvalidDocsPath)
		}
		result[name] = contents
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("resolve SDK docs %s: %w", manifest.Docs.Version, err)
	}
	if len(result) == 0 {
		return nil, fmt.Errorf("resolve SDK docs %s: %w", manifest.Docs.Version, fs.ErrNotExist)
	}
	return result, nil
}

//nolint:wsl_v5,nlreturn // Ownership validation is one ordered security check.
func verifyDocs(root string) error {
	info, err := os.Lstat(root)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("inspect SDK reference: %w", err)
	}
	if !info.IsDir() {
		return fmt.Errorf("SDK reference %s: %w", root, errDocsNotDir)
	}

	encoded, err := os.ReadFile(filepath.Join(root, docsManifest))
	if err != nil {
		return fmt.Errorf("SDK reference ownership: %w", err)
	}
	var state docsState
	if err := json.Unmarshal(encoded, &state); err != nil || state.Warning != "GENERATED BY KARTY. DO NOT EDIT." {
		return errDocsManifest
	}

	openedRoot, err := os.OpenRoot(root)
	if err != nil {
		return fmt.Errorf("open SDK reference: %w", err)
	}
	defer openedRoot.Close()

	actual := make([]string, 0, len(state.Files))
	err = filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}
		name, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return relErr
		}
		name = filepath.ToSlash(name)
		if name == docsManifest {
			return nil
		}
		if entry.Type()&os.ModeSymlink != 0 || !entry.Type().IsRegular() {
			return fmt.Errorf("SDK reference %s: %w", name, errDocsSpecial)
		}
		actual = append(actual, name)
		contents, readErr := openedRoot.ReadFile(name)
		if readErr != nil {
			return readErr
		}
		if state.Files[name] != digest(contents) {
			return fmt.Errorf("SDK reference %s: %w", name, errDocsModified)
		}
		return nil
	})
	if err != nil {
		return err
	}

	expected := make([]string, 0, len(state.Files))
	for name := range state.Files {
		expected = append(expected, name)
	}
	slices.Sort(actual)
	slices.Sort(expected)
	if !slices.Equal(actual, expected) {
		return errDocsFileSet
	}
	return nil
}

//nolint:nlreturn // Keeping the small digest helper compact is clearer.
func digest(contents []byte) string {
	sum := sha256.Sum256(contents)
	return hex.EncodeToString(sum[:])
}
