// Code generated by Karty. DO NOT EDIT.
// WARNING: DO NOT MODIFY THIS FILE DIRECTLY.
// WARNING: MANUAL CHANGES WILL BE OVERWRITTEN.
// Source of truth: internal/build/templates/launcher.js.tmpl.
// Regenerate with: karty build --target web

// Keep launcher bindings out of the browser's global lexical scope.
(() => {
globalThis.kartyLauncherStarted = true;
const element = id => globalThis.document?.getElementById(id);
const state = value => {
  if (globalThis.document?.documentElement) document.documentElement.dataset.kartyState = value;
};
const status = message => { if (element("status")) element("status").textContent = message; };
let ready = false;
const fail = error => {
  state("error");
  console.error("Karty failed:", error);
  if (!element("loading")) return;
  element("loading").hidden = false;
  element("loading").setAttribute("aria-busy", "false");
  element("progress").hidden = true;
  element("retry").hidden = false;
  element("error-detail").hidden = false;
  element("error-detail").textContent = error?.message || String(error);
  status("We couldn’t start the game. Check your connection and try again.");
};
element("fullscreen")?.addEventListener("click", async () => {
  try {
    if (document.fullscreenElement) await document.exitFullscreen();
    else await document.documentElement.requestFullscreen();
  } catch { /* Fullscreen is optional; playing in-page remains available. */ }
});
globalThis.document?.addEventListener("fullscreenchange", () => {
  const label = document.fullscreenElement ? "Exit fullscreen" : "Fullscreen";
  element("fullscreen").textContent = label;
  element("fullscreen").setAttribute("aria-label", label);
});
const fetchChecked = async url => {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Could not load ${url} (HTTP ${response.status})`);
  return response;
};
const loadWasm = async (url, imports) => {
  const response = await fetchChecked(url);
  // Static servers do not always supply application/wasm; keep them usable.
  if (response.headers?.get("Content-Type")?.split(";")[0].trim() === "application/wasm") {
    return WebAssembly.instantiateStreaming(response, imports);
  }
  return WebAssembly.instantiate(await response.arrayBuffer(), imports);
};
const loadClientWasm = async (url, imports) => {
  const response = await fetchChecked(url);
  const module = await WebAssembly.compile(await response.arrayBuffer());
  const sections = WebAssembly.Module.customSections(module, "karty.assets.v1");
  if (sections.length !== 1) throw new Error("The game cartridge asset section is missing or duplicated");
  globalThis.kartyAssetBundle = sections[0];
  const uiSections = WebAssembly.Module.customSections(module, "karty.ui.v1");
  if (uiSections.length > 1) throw new Error("The game UI section is duplicated");
  globalThis.kartyUIBundle = uiSections.length ? uiSections[0] : null;
  const manifests = WebAssembly.Module.customSections(module, "karty.manifest.v1");
  if (manifests.length !== 1) throw new Error("The game cartridge manifest section is missing or duplicated");
  globalThis.kartyManifestBundle = manifests[0];
  return {module, instance: await WebAssembly.instantiate(module, imports)};
};
let go;
let client;
let content = {};
globalThis.kartyConfigureProject = (project, levels) => {
  content = levels || {};
  if (project?.name) {
    document.title = project.name;
    if (element("game-title")) element("game-title").textContent = project.name;
  }
};
const levelRequests = new Map();
const clientMemory = () => new Uint8Array(client.exports.memory.buffer);
const readClientString = (pointer, length) => new TextDecoder().decode(clientMemory().subarray(pointer, pointer + length));
const wasi = {
  fd_write: (fd, iovs, iovsLen, written) => { new DataView(client.exports.memory.buffer).setUint32(written, 0, true); return 0; },
  proc_exit: code => console.warn("client exited", code),
  random_get: (pointer, length) => { crypto.getRandomValues(clientMemory().subarray(pointer, pointer + length)); return 0; },
  sched_yield: () => 0,
  poll_oneoff: () => 0,
  clock_time_get: () => 0,
};
const imports = {
  wasi_snapshot_preview1: wasi,
  karty: {
    log: (pointer, length) => globalThis.kartyHostLog(readClientString(pointer, length)),
    play_sound: soundID => globalThis.kartyHostPlaySound(soundID),
    action: actionID => globalThis.kartyHostAction(actionID),
    submit_commands: (pointer, length) => {
      pointer >>>= 0; length >>>= 0;
      const memory = clientMemory();
      if (length > 65536 || pointer > memory.length || length > memory.length - pointer) {
        globalThis.kartyHostSubmitCommands(new Uint8Array());
        return;
      }
      globalThis.kartyHostSubmitCommands(memory.subarray(pointer, pointer + length));
    },
  },
};
const hex = bytes => Array.from(bytes, value => value.toString(16).padStart(2, "0")).join("");
globalThis.kartyCancelLevel = requestID => {
  levelRequests.get(requestID)?.abort();
  levelRequests.delete(requestID);
};
globalThis.kartyRequestLevel = (requestID, name) => {
  const entry = content[name];
  if (!entry) {
    globalThis.kartyHostLevelFailed(requestID, 1, `Level ${name} is not declared by the game cartridge`);
    return;
  }
  const abort = new AbortController();
  levelRequests.set(requestID, abort);
  Promise.resolve().then(async () => {
    const response = await fetch(entry.artifact, {signal: abort.signal});
    if (!response.ok) throw new Error(`Could not load ${entry.artifact} (HTTP ${response.status})`);
    const bytes = await response.arrayBuffer();
    if (bytes.byteLength !== entry.size) throw new Error("Level artifact size does not match the game manifest");
    const digest = hex(new Uint8Array(await crypto.subtle.digest("SHA-256", bytes)));
    if (digest !== entry.contentSha256) throw new Error("Level artifact hash does not match the game manifest");
    const result = await WebAssembly.instantiate(bytes, {});
    const exports = result.instance.exports;
    if (typeof exports.karty_level_abi_version !== "function" || exports.karty_level_abi_version() !== entry.envelopeVersion) {
      globalThis.kartyHostLevelFailed(requestID, 3, "Level ABI version is unsupported");
      return;
    }
    if (typeof exports.karty_level_data_pointer !== "function" || typeof exports.karty_level_data_length !== "function" || !exports.memory) {
      globalThis.kartyHostLevelFailed(requestID, 2, "Level cartridge exports are invalid");
      return;
    }
    const pointer = exports.karty_level_data_pointer() >>> 0;
    const length = exports.karty_level_data_length() >>> 0;
    const memory = new Uint8Array(exports.memory.buffer);
    if (!length || pointer > memory.length || length > memory.length - pointer) {
      globalThis.kartyHostLevelFailed(requestID, 2, "Level cartridge data range is invalid");
      return;
    }
    globalThis.kartyHostLevelLoaded(requestID, memory.slice(pointer, pointer + length));
  }).catch(error => {
    if (error?.name !== "AbortError") globalThis.kartyHostLevelFailed(requestID, 7, error?.message || String(error));
  }).finally(() => levelRequests.delete(requestID));
};
Promise.resolve().then(() => {
  state("loading-cartridge");
  status("Loading game cartridge…");
  go = new Go();
  return loadClientWasm("game.kart?v=d2b44a3542e4fe33", imports);
})
  .then(result => {
    client = result.instance;
    globalThis.kartyClientInitialize = () => { client.exports.karty_register(); client.exports.initialize(); };
    globalThis.kartyClientUpdate = (frame, events) => {
      const pointer = client.exports.event_buffer() >>> 0;
      const memory = clientMemory();
      if (events.length > 65536 || pointer > memory.length || events.length > memory.length - pointer) {
        throw new Error("invalid client event buffer");
      }
      memory.set(events, pointer);
      client.exports.update(frame, events.length);
      if (globalThis.document?.documentElement) document.documentElement.dataset.kartyFrame = String(frame);
      if (!ready) {
        ready = true;
        state("running");
        if (element("loading")) {
          element("loading").setAttribute("aria-busy", "false");
          element("loading").hidden = true;
          element("fullscreen").hidden = !document.fullscreenEnabled;
          document.querySelector("canvas")?.focus();
        }
      }
    };
    globalThis.kartyClientShutdown = () => client.exports.shutdown();
    client.exports._initialize();
    status("Starting the renderer…");
    return loadWasm("karty-host.wasm?v=acdd7af686530d85", go.importObject);
  })
  .then(result => go.run(result.instance))
  .then(() => { throw new Error("The game has stopped. Reload to play again."); })
  .catch(fail);
})();
