package schema

import (
	"encoding/json"
	"fmt"
	"net/url"
	"slices"

	"github.com/google/jsonschema-go/jsonschema"
)

// Level adds level-local texture/material and authored prefab reference choices.
// Abstract prefab materials must be declared as an instance override's "from";
// final expanded material resolution remains the compiler's responsibility.
func Level(value any, textures []string) *jsonschema.Schema {
	root, _ := value.(map[string]any)
	prefabs := records(root["prefabs"])
	prefabNames := make([]string, 0, len(prefabs))
	aliases := make([]string, 0)
	collect := func(scope map[string]any) {
		for _, instance := range records(scope["instances"]) {
			for _, override := range records(instance["materials"]) {
				if name, ok := override["from"].(string); ok {
					aliases = append(aliases, name)
				}
			}
		}
	}
	collect(root)

	for _, prefab := range prefabs {
		if id, ok := prefab["id"].(string); ok {
			prefabNames = append(prefabNames, id)
		}

		collect(prefab)
	}

	materials := sortedChoices(textures)
	prefabMaterials := sortedChoices(append(slices.Clone(textures), aliases...))

	fields := scopeCatalog(materials, sortedChoices(prefabNames))
	fields["prefabs"] = &jsonschema.Schema{
		Items: &jsonschema.Schema{
			Properties: scopeCatalog(prefabMaterials, sortedChoices(prefabNames)),
		},
	}

	return &jsonschema.Schema{
		Schema:     draft,
		Title:      "Karty level world",
		Comment:    "Generated by karty schema from this level's textures and world declarations. Regenerate after renaming assets or prefabs.",
		Ref:        "../" + BaseFilename,
		Properties: fields,
	}
}

func sortedChoices(names []string) *jsonschema.Schema {
	names = slices.Clone(names)
	slices.Sort(names)
	names = slices.Compact(names)

	return choice(names...)
}

func scopeCatalog(materials, prefabs *jsonschema.Schema) map[string]*jsonschema.Schema {
	bands := &jsonschema.Schema{Properties: map[string]*jsonschema.Schema{
		"top":    {Properties: map[string]*jsonschema.Schema{"texture": materials}},
		"bottom": {Properties: map[string]*jsonschema.Schema{"texture": materials}},
	}}
	content := &jsonschema.Schema{Properties: map[string]*jsonschema.Schema{
		"actor": {Properties: map[string]*jsonschema.Schema{"sprite": {Properties: map[string]*jsonschema.Schema{"texture": materials}}}},
	}}

	return map[string]*jsonschema.Schema{
		"rooms": {Items: &jsonschema.Schema{Properties: map[string]*jsonschema.Schema{
			"floor_material":    materials,
			"ceiling_material":  materials,
			"wall_bands":        bands,
			"floor_secondary":   {Properties: map[string]*jsonschema.Schema{"texture": materials}},
			"ceiling_secondary": {Properties: map[string]*jsonschema.Schema{"texture": materials}},
			"wall_secondary":    {Properties: map[string]*jsonschema.Schema{"texture": materials}},
			"boundary": {
				Items: &jsonschema.Schema{
					Properties: map[string]*jsonschema.Schema{
						"material":  materials,
						"bands":     bands,
						"secondary": {Properties: map[string]*jsonschema.Schema{"texture": materials}},
					},
				},
			},
			"contents": {Items: content},
		}}},
		"solids": {Items: &jsonschema.Schema{Properties: map[string]*jsonschema.Schema{
			"side_material": materials, "top_material": materials, "bottom_material": materials,
		}}},
		"contents": {Items: content},
		"instances": {Items: &jsonschema.Schema{Properties: map[string]*jsonschema.Schema{
			"prefab": prefabs, "materials": {Items: &jsonschema.Schema{Properties: map[string]*jsonschema.Schema{"to": materials}}},
		}}},
	}
}

func records(value any) []map[string]any {
	values, _ := value.([]any)

	result := make([]map[string]any, 0, len(values))
	for _, value := range values {
		if object, ok := value.(map[string]any); ok {
			result = append(result, object)
		}
	}

	return result
}

// Validate uses the same generated schemas as the editor, resolving the shared
// base in memory. It never trusts edited generated files or fetches remote URLs.
func Validate(value any, level *jsonschema.Schema) error {
	// A JSON round trip gives each schema location its own node, including
	// catalog enums reused for multiple material fields.
	data, err := Encode(level)
	if err != nil {
		return err
	}

	var isolated jsonschema.Schema
	if err = json.Unmarshal(data, &isolated); err != nil {
		return err
	}

	resolved, err := isolated.Resolve(&jsonschema.ResolveOptions{
		BaseURI: "file:///schemas/levels/level.schema.json",
		Loader: func(uri *url.URL) (*jsonschema.Schema, error) {
			if uri.String() != "file:///schemas/"+BaseFilename {
				return nil, fmt.Errorf("%w: unexpected schema reference %q", ErrValidation, uri)
			}

			base, encodeErr := Encode(Base())
			if encodeErr != nil {
				return nil, encodeErr
			}

			var s jsonschema.Schema
			if decodeErr := json.Unmarshal(base, &s); decodeErr != nil {
				return nil, decodeErr
			}

			return &s, nil
		},
	})
	if err != nil {
		return fmt.Errorf("%w: resolve schema: %w", ErrValidation, err)
	}

	if err := resolved.Validate(value); err != nil {
		return fmt.Errorf("%w: %w", ErrValidation, err)
	}

	return nil
}
