// Package schema generates editor schemas and validates authored world YAML.
// The field vocabulary comes from the public SDK; parsing remains CLI-owned.
package schema

import (
	"encoding/json"
	"maps"
	"reflect"
	"strings"

	"github.com/google/jsonschema-go/jsonschema"
	"github.com/karty-game/karty-sdk/format/world"
	"github.com/karty-game/karty-sdk/format/worldsource"
)

const (
	BaseFilename = "worldsource.base.schema.json"
	draft        = "https://json-schema.org/draft/2020-12/schema"
)

type grammar struct{ definitions map[string]*jsonschema.Schema }

// Base describes all supported source versions, without project references.
func Base() *jsonschema.Schema {
	builder := grammar{definitions: make(map[string]*jsonschema.Schema)}
	root := builder.shape(reflect.TypeFor[worldsource.Document]())
	root.Schema = draft
	root.Title = "Karty world"
	root.Comment = "Generated by karty schema. Edit the world YAML and level.toml, then regenerate."
	root.Defs = builder.definitions

	builder.constraints()

	return root
}

// Encode produces deterministic, readable schema files.
func Encode(s *jsonschema.Schema) ([]byte, error) {
	data, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return nil, err
	}

	return append(data, '\n'), nil
}

func (g *grammar) shape(fieldType reflect.Type) *jsonschema.Schema {
	//nolint:exhaustive // Only public world source field kinds are supported; unsupported kinds fail explicitly.
	switch fieldType.Kind() {
	case reflect.Pointer:
		return &jsonschema.Schema{If: &jsonschema.Schema{Not: &jsonschema.Schema{Type: "null"}}, Then: g.shape(fieldType.Elem())}
	case reflect.Struct:
		ref := &jsonschema.Schema{Ref: "#/$defs/" + fieldType.Name()}
		if _, exists := g.definitions[fieldType.Name()]; exists {
			return ref
		}

		s := &jsonschema.Schema{Type: "object", Properties: make(map[string]*jsonschema.Schema), AdditionalProperties: deny()}

		g.definitions[fieldType.Name()] = s
		for field := range fieldType.Fields() {
			name, _, _ := strings.Cut(field.Tag.Get("yaml"), ",")
			s.Properties[name] = g.shape(field.Type)
		}

		return ref
	case reflect.Slice:
		return &jsonschema.Schema{Types: []string{"array", "null"}, Items: g.shape(fieldType.Elem())}
	case reflect.String:
		return &jsonschema.Schema{Type: "string"}
	case reflect.Bool:
		return &jsonschema.Schema{Type: "boolean"}
	case reflect.Uint16, reflect.Uint32:
		return &jsonschema.Schema{Type: "integer", Minimum: new(float64(0))}
	case reflect.Float64:
		return number(-worldsource.MaxCoordinate, worldsource.MaxCoordinate)
	default:
		panic("unsupported public world source field: " + fieldType.String())
	}
}

func deny() *jsonschema.Schema { return &jsonschema.Schema{Not: &jsonschema.Schema{}} }

func number(minimum, maximum float64) *jsonschema.Schema {
	return &jsonschema.Schema{Type: "number", Minimum: &minimum, Maximum: &maximum}
}

func identifier() *jsonschema.Schema {
	return &jsonschema.Schema{Type: "string", MinLength: new(1), MaxLength: new(worldsource.MaxIdentifierBytes)}
}

func choice(values ...string) *jsonschema.Schema {
	s := &jsonschema.Schema{Type: "string", Enum: make([]any, len(values))}
	for i, value := range values {
		s.Enum[i] = value
	}

	return s
}

func (g *grammar) constraints() {
	for _, definition := range g.definitions {
		for name, property := range definition.Properties {
			switch name {
			case "id",
				"kind",
				"prefab",
				"texture",
				"from",
				"to",
				"material",
				"floor_material",
				"ceiling_material",
				"side_material",
				"top_material",
				"bottom_material":
				definition.Properties[name] = identifier()
			case "rooms":
				property.MaxItems = new(worldsource.MaxRooms)
			case "prefabs":
				property.MaxItems = new(worldsource.MaxPrefabs)
			case "instances":
				property.MaxItems = new(worldsource.MaxInstances)
			case "connections":
				property.MaxItems = new(worldsource.MaxConnections)
			case "ports":
				property.MaxItems = new(worldsource.MaxPorts)
			case "contents":
				property.MaxItems = new(worldsource.MaxContents)
			case "solids":
				property.MaxItems = new(world.MaxStaticSolids)
			case "lights":
				property.MaxItems = new(worldsource.MaxLights)
			case "boundary":
				property.Type, property.Types = "array", nil
				property.MinItems, property.MaxItems = new(3), new(worldsource.MaxEdgesPerRoom)
			case "footprint":
				property.Type, property.Types = "array", nil
				property.MinItems, property.MaxItems = new(3), new(world.MaxSolidVertices)
			case "materials":
				property.MaxItems = new(worldsource.MaxMaterialOverrides)
			case "tags":
				property.MaxItems = new(worldsource.MaxTags)
				property.Items = &jsonschema.Schema{Type: "string", MinLength: new(1), MaxLength: new(worldsource.MaxTagBytes)}
			}
		}
	}

	for _, scope := range []string{"Document", "Prefab"} {
		for _, field := range []string{"solids", "contents"} {
			g.definitions[scope].Properties[field].Type = "array"
			g.definitions[scope].Properties[field].Types = nil
		}
	}

	for name, required := range map[string][]string{
		"Document": {"version"}, "Room": {"id", "boundary", "floor_material", "ceiling_material"},
		"Edge": {"id", "start", "end", "material"}, "Content": {"id", "kind"},
		"Prefab": {"id"}, "Instance": {"id", "prefab"}, "MaterialOverride": {"from", "to"},
		"Connection": {"id", "a", "b"}, "Port": {"id", "endpoint"},
		"Solid":  {"id", "footprint", "side_material", "top_material", "bottom_material"},
		"Sprite": {"texture", "facing", "alpha", "width", "height"}, "Lighting": {"version"},
		"PointLight": {"id", "radius"}, "LightMotion": {"version", "period_seconds"},
	} {
		g.definitions[name].Required = required
	}

	set := func(name, field string, s *jsonschema.Schema) { g.definitions[name].Properties[field] = s }
	set(
		"Document",
		"version",
		&jsonschema.Schema{Type: "integer", Minimum: new(float64(worldsource.LegacyVersion)), Maximum: new(float64(worldsource.Version))},
	)
	set(
		"Connection",
		"direction",
		choice("", string(worldsource.PortalBoth), string(worldsource.PortalAToB), string(worldsource.PortalBToA)),
	)
	set("Sprite", "facing", choice("camera-facing", "upright", "cross", "fixed"))
	set("Sprite", "alpha", choice("cutout", "blend"))

	for _, field := range []string{"width", "height"} {
		set("Sprite", field, &jsonschema.Schema{Type: "number", ExclusiveMinimum: new(float64(0)), Maximum: new(worldsource.MaxCoordinate)})
	}

	for _, field := range []string{"origin_x", "origin_y"} {
		set("Sprite", field, number(0, 1))
	}

	set("Transform", "scale", number(0, worldsource.MaxCoordinate))
	set("Actor", "scale", vector("xyz", 0, worldsource.MaxCoordinate))
	set("UVSettings", "mode", choice("", string(worldsource.UVTriplanar), string(worldsource.UVPlanar), string(worldsource.UVWrap)))
	set("UVSettings", "anchor", choice("", string(worldsource.UVWorld), string(worldsource.UVTop), string(worldsource.UVBottom)))
	set(
		"UVSettings",
		"scale",
		&jsonschema.Schema{AnyOf: []*jsonschema.Schema{vector("xy", worldsource.MinUVScale, worldsource.MaxCoordinate), {Type: "null"}}},
	)
	set("Lighting", "version", &jsonschema.Schema{Type: "integer", Enum: []any{world.LightingVersion}})
	set("Lighting", "ambient", vector("xyz", 0, 1))

	for _, field := range []string{"positive_x", "negative_x", "positive_y", "negative_y", "positive_z", "negative_z"} {
		set("AmbientCube", field, vector("xyz", 0, 1))
	}

	set("PointLight", "color", vector("xyz", 0, 1))
	set("PointLight", "radius", number(worldsource.MinLightRadius, worldsource.MaxCoordinate))
	set("LightMotion", "version", &jsonschema.Schema{Type: "integer", Enum: []any{1}})
	set("LightMotion", "period_seconds", number(0.1, 3600))

	g.definitions["Endpoint"].OneOf = []*jsonschema.Schema{
		{
			Required: []string{"room", "edge"},
			Properties: map[string]*jsonschema.Schema{
				"room":     identifier(),
				"edge":     identifier(),
				"instance": choice(""),
				"port":     choice(""),
			},
		},
		{
			Required: []string{"instance", "port"},
			Properties: map[string]*jsonschema.Schema{
				"instance": identifier(),
				"port":     identifier(),
				"room":     choice(""),
				"edge":     choice(""),
			},
		},
	}
	g.versionRules()
}

func vector(axes string, minimum, maximum float64) *jsonschema.Schema {
	properties := make(map[string]*jsonschema.Schema, len(axes))
	for _, axis := range axes {
		properties[string(axis)] = number(minimum, maximum)
	}

	return &jsonschema.Schema{Type: "object", Properties: properties, AdditionalProperties: deny()}
}

func (g *grammar) versionRules() {
	// Conditions walk the same finite authored scopes; prefab instantiation is
	// checked by the semantic compiler rather than recursive schema evaluation.
	document := g.definitions["Document"]

	for _, scope := range []string{"Document", "Prefab"} {
		for _, field := range []string{"rooms", "instances", "solids", "contents"} {
			g.definitions[scope].AnyOf = append(g.definitions[scope].AnyOf, &jsonschema.Schema{
				Required: []string{field}, Properties: map[string]*jsonschema.Schema{field: {Type: "array", MinItems: new(1)}},
			})
		}
	}

	for _, rule := range []struct {
		version uint16
		fields  map[string]*jsonschema.Schema
	}{
		{worldsource.ActorVersion, map[string]*jsonschema.Schema{
			"instances": {Items: &jsonschema.Schema{Properties: map[string]*jsonschema.Schema{"tags": {MaxItems: new(0)}}}},
			"rooms":     {Items: &jsonschema.Schema{Properties: map[string]*jsonschema.Schema{"contents": {Items: &jsonschema.Schema{Properties: map[string]*jsonschema.Schema{"actor": {Type: "null"}}}}}}},
		}},
		{worldsource.PortalVersion, map[string]*jsonschema.Schema{"connections": {Items: &jsonschema.Schema{Properties: map[string]*jsonschema.Schema{"direction": choice("", "both"), "non_euclidean": {Enum: []any{false}}}}}}},
		{worldsource.LightingVersion, map[string]*jsonschema.Schema{"lighting": {Type: "null"}}},
		{worldsource.MappingVersion, map[string]*jsonschema.Schema{
			"uv": {Type: "null"}, "rooms": {Items: &jsonschema.Schema{Properties: map[string]*jsonschema.Schema{
				"floor_uv": {Type: "null"}, "ceiling_uv": {Type: "null"}, "wall_uv": {Type: "null"},
				"boundary": {Items: &jsonschema.Schema{Properties: map[string]*jsonschema.Schema{"uv": {Type: "null"}}}},
			}}},
		}},
		{worldsource.SolidsVersion, map[string]*jsonschema.Schema{"solids": deny(), "contents": deny()}},
	} {
		fields := rule.fields
		// Lighting and root UV are not prefab fields; restricting their absence
		// here is harmless because the base rejects unknown prefab fields.
		prefabScope := &jsonschema.Schema{Properties: fields}
		thenFields := maps.Clone(fields)
		thenFields["prefabs"] = &jsonschema.Schema{Items: prefabScope}
		document.AllOf = append(document.AllOf, &jsonschema.Schema{
			If:   &jsonschema.Schema{Properties: map[string]*jsonschema.Schema{"version": {Maximum: new(float64(rule.version - 1))}}},
			Then: &jsonschema.Schema{Properties: thenFields},
		})
	}

	// Horizontal surfaces cannot wrap, and solid sides only support planar/world.
	horizontal := &jsonschema.Schema{
		Properties: map[string]*jsonschema.Schema{"mode": choice("", "triplanar", "planar"), "anchor": choice("", "world")},
	}
	for _, field := range []string{"floor_uv", "ceiling_uv"} {
		g.definitions["Room"].Properties[field].AllOf = []*jsonschema.Schema{horizontal}
	}

	for _, field := range []string{"top_uv", "bottom_uv"} {
		g.definitions["Solid"].Properties[field].AllOf = []*jsonschema.Schema{horizontal}
	}

	g.definitions["Solid"].Properties["side_uv"].AllOf = []*jsonschema.Schema{
		{Properties: map[string]*jsonschema.Schema{"mode": choice("", "planar"), "anchor": choice("", "world")}},
	}
}
