// Package actionbuild derives one typed action catalog, editor schema and
// same-package invocation adapters from explicit game function declarations.
package actionbuild

import (
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type Parameter struct {
	Name string `json:"name"`
	Type string `json:"type"`
}
type Declaration struct {
	ID         string      `json:"id"`
	Kind       string      `json:"kind"`
	Function   string      `json:"function"`
	Source     string      `json:"source"`
	Parameters []Parameter `json:"parameters"`
}
type Level struct {
	Name, Directory string
	Actors          map[string]bool
}
type Result struct {
	Source, Catalog, Schema []byte
	LevelSchemas            map[string][]byte
}

// Discover reads only confined game sources. Annotated functions must be
// top-level, non-generic functions with a typed ActionContext and bounded args.
func Discover(directory, module string) ([]Declaration, error) {
	source, err := os.OpenRoot(filepath.Join(directory, "src"))
	if err != nil {
		return nil, err
	}
	defer source.Close()

	declarations := []Declaration{}
	seen := map[string]bool{}
	files := 0
	err = fs.WalkDir(source.FS(), ".", func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}

		if entry.Type()&os.ModeSymlink != 0 {
			return invalidActions("action discovery rejects symlink %s", path)
		}

		if entry.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		files++
		if files > maxSourceFiles {
			return invalidActions("game source file limit exceeded")
		}

		contents, err := source.ReadFile(path)
		if err != nil {
			return err
		}

		if len(contents) > 1<<20 {
			return invalidActions("source %s exceeds size bound", path)
		}

		found, err := discoverFile(path, contents, module, seen)
		if err != nil {
			return err
		}

		declarations = append(declarations, found...)

		return nil
	})

	sort.Slice(declarations, func(i, j int) bool { return declarations[i].ID < declarations[j].ID })

	if len(declarations) > maxDeclarations {
		return nil, invalidActions("action catalog limit exceeded")
	}

	return declarations, err
}
func typeName(expr ast.Expr, engineAlias string) string {
	switch value := expr.(type) {
	case *ast.Ident:
		if value.Name == "ActionContext" || value.Name == "WorldActorRef" {
			return "unsupported"
		}

		return value.Name
	case *ast.SelectorExpr:
		if owner, ok := value.X.(*ast.Ident); ok && owner.Name == engineAlias {
			return value.Sel.Name
		}
	}

	return "unsupported"
}

func Compile(directory, module string, declarations []Declaration, levels []Level, contract []byte) (Result, error) {
	var result Result

	schema, defs, step, base, err := actionSchema(contract)
	if err != nil {
		return result, err
	}

	delete(schema, "$id") // Resolve project-specific schemas by their file URI.

	choices := []any{base[2]}

	catalog := map[string]Declaration{}
	for _, declaration := range declarations {
		catalog[declaration.ID] = declaration

		index := 0
		if declaration.Kind == "condition" {
			index = 1
		}

		choice, err := declarationSchema(base[index], declaration, defs)
		if err != nil {
			return result, err
		}

		choices = append(choices, choice)
	}

	step["oneOf"] = choices

	result.Schema, err = json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return result, err
	}

	result.Catalog, err = json.MarshalIndent(struct {
		Version int           `json:"version"`
		Actions []Declaration `json:"actions"`
	}{1, declarations}, "", "  ")
	if err != nil {
		return result, err
	}

	var source strings.Builder
	source.WriteString(
		"// Code generated by Karty. DO NOT EDIT.\n// WARNING: MANUAL CHANGES WILL BE OVERWRITTEN.\n// Source of truth: src/ action declarations and levels/*/actions.json.\n// Generator: CLI internal/actionbuild/. Regenerate with karty build.\npackage main\nimport kartyEngine " + strconv.Quote(
			module+"/.karty/engine",
		) + "\n",
	)
	source.WriteString(
		"func StartAuthoredSequence(level kartyEngine.LevelHandle, levelName, name string) (kartyEngine.SequenceID,error) {\n switch levelName {\n",
	)

	found := false
	result.LevelSchemas = map[string][]byte{}

	for _, built := range levels {
		root, err := os.OpenRoot(built.Directory)
		if err != nil {
			return result, err
		}

		contents, err := root.ReadFile("actions.json")
		root.Close()

		missing := os.IsNotExist(err)
		if err != nil && !missing {
			return result, err
		}

		levelSchema, err := schemaForLevel(schema, built)
		if err != nil {
			return result, err
		}

		// The directory name is a confined output key, not a runtime level identity.
		key := filepath.Base(built.Directory)

		result.LevelSchemas[key], err = json.MarshalIndent(levelSchema, "", "  ")
		if err != nil {
			return result, err
		}

		if missing {
			continue
		}

		found = true

		document, err := readJSON(contents)
		if err != nil {
			return result, fmt.Errorf("%s/actions.json: %w", built.Directory, err)
		}

		if err = validateSchema(document, schema, schema, "actions.json", 0); err != nil {
			return result, fmt.Errorf("%s: %w", built.Directory, err)
		}

		if err := compileLevelSequences(&source, document, catalog, built); err != nil {
			return result, err
		}
	}

	source.WriteString("}\n return 0,kartyEngine.ActionError(\"authored sequence not found: \"+levelName+\"/\"+name)\n}\n")

	if !found && len(declarations) == 0 {
		return result, nil
	}

	result.Source, err = format.Source([]byte(source.String()))

	return result, err
}
func parameterSchema(kind string, defs map[string]any) map[string]any {
	switch kind {
	case "bool":
		return map[string]any{"type": "boolean"}
	case "string":
		return map[string]any{"type": "string", "maxLength": maxStringBytes}
	case "int32":
		return map[string]any{"type": "integer", "minimum": math.MinInt32, "maximum": math.MaxInt32}
	case "uint32":
		return map[string]any{"type": "integer", "minimum": 0, "maximum": float64(math.MaxUint32)}
	case "float32":
		return map[string]any{"type": "number", "minimum": -float64(math.MaxFloat32), "maximum": float64(math.MaxFloat32)}
	default:
		value, _ := defs["value"].(map[string]any)

		variants, _ := value["oneOf"].([]any)
		if len(variants) != actionValueVariants {
			return nil
		}

		actor, _ := variants[3].(map[string]any)

		return actor
	}
}
func compileSteps(steps []any, catalog map[string]Declaration, level Level, depth int, count *int, path string) (string, error) {
	if len(steps) > 0 && depth > 16 {
		return "", invalidActions("%s: branch depth exceeds 16", path)
	}

	var source strings.Builder
	source.WriteString("[]kartyEngine.SequenceStep{")

	for index, value := range steps {
		*count++
		if *count > maxSteps {
			return "", invalidActions("%s: step limit exceeded", path)
		}

		if err := compileStep(&source, value, catalog, level, depth, count, fmt.Sprintf("%s/%d", path, index)); err != nil {
			return "", err
		}
	}

	source.WriteString("}")

	return source.String(), nil
}

func validArgumentName(name string) bool {
	if len(name) == 0 || len(name) > 128 || name == "_" {
		return false
	}

	for i, r := range name {
		if (r < 'a' || r > 'z') && (r < 'A' || r > 'Z') && r != '_' && (i <= 0 || r < '0' || r > '9') {
			return false
		}
	}

	return true
}

func discoverFile(path string, contents []byte, module string, seen map[string]bool) ([]Declaration, error) {
	declarations := []Declaration{}
	set := token.NewFileSet()

	file, err := parser.ParseFile(set, path, contents, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	engineAlias := ""

	for _, item := range file.Imports {
		importPath, _ := strconv.Unquote(item.Path.Value)
		if importPath == module+"/.karty/engine" {
			engineAlias = "engine"
			if item.Name != nil {
				engineAlias = item.Name.Name
			}
		}
	}

	for _, item := range file.Decls {
		function, ok := item.(*ast.FuncDecl)
		if !ok || function.Doc == nil {
			continue
		}

		kind, identifier, err := actionAnnotation(function.Doc)
		if err != nil {
			return nil, invalidActions("%s: %s", set.Position(function.Pos()), err)
		}

		if kind == "" {
			continue
		}

		declaration, err := discoverFunction(path, file, function, set, contents, engineAlias, kind, identifier, seen)
		if err != nil {
			return nil, err
		}

		declarations = append(declarations, declaration)
	}

	return declarations, nil
}

func actionAnnotation(doc *ast.CommentGroup) (string, string, error) {
	kind, identifier := "", ""

	for _, comment := range doc.List {
		annotation := strings.TrimSpace(strings.TrimPrefix(comment.Text, "//"))
		if !strings.HasPrefix(annotation, "karty:action") && !strings.HasPrefix(annotation, "karty:condition") {
			continue
		}

		parts := strings.Fields(annotation)
		if len(parts) != 2 || kind != "" || (parts[0] != "karty:action" && parts[0] != "karty:condition") {
			return "", "", invalidActions("invalid action declaration")
		}

		kind = strings.TrimPrefix(parts[0], "karty:")
		identifier = parts[1]
	}

	return kind, identifier, nil
}

func discoverFunction(
	path string,
	file *ast.File,
	function *ast.FuncDecl,
	set *token.FileSet,
	contents []byte,
	engineAlias, kind, identifier string,
	seen map[string]bool,
) (Declaration, error) {
	location := set.Position(function.Pos()).String()
	fail := func(message string) error { return invalidActions("%s: %s", location, message) }

	if err := checkActionPlatform(path, file, contents); err != nil {
		return Declaration{}, fail(err.Error())
	}

	if filepath.Dir(path) != "." || function.Body == nil || file.Name.Name != "main" || function.Recv != nil ||
		function.Type.TypeParams != nil ||
		engineAlias == "" ||
		engineAlias == "." ||
		engineAlias == "_" {
		return Declaration{}, fail("actions require a top-level game function and a named engine import")
	}

	if len(identifier) > 128 || identifier == "" || seen[identifier] {
		return Declaration{}, fail("duplicate or invalid action identifier " + identifier)
	}

	seen[identifier] = true
	if !validActionIdentifier(identifier) {
		return Declaration{}, fail("invalid action identifier " + identifier)
	}

	params, err := actionParameters(function, engineAlias, kind)
	if err != nil {
		return Declaration{}, fail(err.Error())
	}

	return Declaration{identifier, kind, function.Name.Name, "src/" + location, params}, nil
}

func checkActionPlatform(path string, file *ast.File, contents []byte) error {
	fail := func(message string) error { return invalidActions("%s", message) }

	for _, group := range file.Comments {
		if group.Pos() < file.Package &&
			(strings.Contains(group.Text(), "go:build") || strings.Contains(string(contents[group.Pos()-1:group.End()-1]), "//go:build")) {
			return fail("action declarations cannot use build constraints")
		}
	}

	base := strings.TrimSuffix(filepath.Base(path), ".go")
	for _, suffix := range []string{"_aix", "_android", "_darwin", "_dragonfly", "_freebsd", "_illumos", "_ios", "_js", "_linux", "_netbsd", "_openbsd", "_plan9", "_solaris", "_wasip1", "_windows", "_386", "_amd64", "_arm", "_arm64", "_loong64", "_mips", "_mipsle", "_mips64", "_mips64le", "_ppc64", "_ppc64le", "_riscv64", "_s390x", "_wasm"} {
		if strings.HasSuffix(base, suffix) {
			return fail("action declarations need platform-independent source filenames")
		}
	}

	return nil
}

func actionParameters(function *ast.FuncDecl, engineAlias, kind string) ([]Parameter, error) {
	params := []Parameter{}
	types := []string{}

	for _, field := range function.Type.Params.List {
		typeName := typeName(field.Type, engineAlias)
		for _, name := range field.Names {
			params = append(params, Parameter{name.Name, typeName})
			types = append(types, typeName)
		}
	}

	if len(types) == 0 || types[0] != "ActionContext" || len(types) > 17 {
		return nil, invalidActions("first parameter must be engine.ActionContext; at most 16 action arguments")
	}

	paramNames := map[string]bool{}

	for _, param := range params[1:] {
		switch param.Type {
		case "bool", "string", "int32", "uint32", "float32", "WorldActorRef":
		default:
			return nil, invalidActions("unsupported argument type %s", param.Type)
		}

		if !validArgumentName(param.Name) || paramNames[param.Name] {
			return nil, invalidActions("arguments need distinct ASCII names of at most 128 bytes")
		}

		paramNames[param.Name] = true
	}

	results := []string{}

	if function.Type.Results != nil {
		for _, field := range function.Type.Results.List {
			n := len(field.Names)
			if n == 0 {
				n = 1
			}

			for range n {
				results = append(results, typeName(field.Type, engineAlias))
			}
		}
	}

	expected := "error"
	if kind == "condition" {
		expected = "bool,error"
	}

	if strings.Join(results, ",") != expected {
		return nil, invalidActions("expected return types %s", expected)
	}

	return params[1:], nil
}

func validActionIdentifier(identifier string) bool {
	for index, letter := range identifier {
		alpha := letter >= 'a' && letter <= 'z' || letter >= 'A' && letter <= 'Z'

		tail := index > 0 && (letter >= '0' && letter <= '9' || letter == '.' || letter == '_' || letter == '-')
		if !alpha && !tail {
			return false
		}
	}

	return identifier != ""
}

func actionSchema(contract []byte) (map[string]any, map[string]any, map[string]any, []any, error) {
	value, err := readJSON(contract)
	if err != nil {
		return nil, nil, nil, nil, err
	}

	schema, validSchema := value.(map[string]any)
	if !validSchema {
		return nil, nil, nil, nil, invalidActions("invalid SDK action schema")
	}

	if err = checkSchema(schema); err != nil {
		return nil, nil, nil, nil, err
	}

	defs, valid := schema["$defs"].(map[string]any)
	if !valid {
		return nil, nil, nil, nil, invalidActions("SDK action schema requires definitions")
	}

	step, valid := defs["step"].(map[string]any)
	if !valid {
		return nil, nil, nil, nil, invalidActions("SDK action schema requires step definitions")
	}

	base, valid := step["oneOf"].([]any)
	if !valid || len(base) != 3 {
		return nil, nil, nil, nil, invalidActions("unsupported SDK action step schema")
	}

	for _, choice := range base {
		object, isObject := choice.(map[string]any)
		if !isObject {
			return nil, nil, nil, nil, invalidActions("SDK action step must be an object")
		}

		if _, valid := object["properties"].(map[string]any); !valid {
			return nil, nil, nil, nil, invalidActions("SDK action step requires properties")
		}
	}

	valueDef, valid := defs["value"].(map[string]any)
	if !valid {
		return nil, nil, nil, nil, invalidActions("SDK action schema requires argument definitions")
	}

	values, valid := valueDef["oneOf"].([]any)
	if !valid || len(values) != 4 {
		return nil, nil, nil, nil, invalidActions("unsupported SDK action argument schema")
	}

	actor, isActor := values[3].(map[string]any)
	if !isActor {
		return nil, nil, nil, nil, invalidActions("SDK actor schema must be an object")
	}

	actorProps, valid := actor["properties"].(map[string]any)
	if !valid {
		return nil, nil, nil, nil, invalidActions("SDK actor schema requires properties")
	}

	if _, valid := actorProps["actor"].(map[string]any); !valid {
		return nil, nil, nil, nil, invalidActions("SDK actor schema requires identity")
	}

	return schema, defs, step, base, nil
}

func declarationSchema(base any, declaration Declaration, defs map[string]any) (map[string]any, error) {
	choice, err := copySchema(base)
	if err != nil {
		return nil, err
	}

	props, hasProps := choice["properties"].(map[string]any)
	if !hasProps {
		return nil, invalidActions("step schema requires properties")
	}

	props[declaration.Kind] = map[string]any{"const": declaration.ID}
	argProps := map[string]any{}
	required := []any{}

	for _, parameter := range declaration.Parameters {
		argProps[parameter.Name] = parameterSchema(parameter.Type, defs)
		required = append(required, parameter.Name)
	}

	props["args"] = map[string]any{"type": "object", "properties": argProps, "required": required, "additionalProperties": false}

	return choice, nil
}

func copySchema(value any) (map[string]any, error) {
	encoded, err := json.Marshal(value)
	if err != nil {
		return nil, err
	}

	copied, err := readJSON(encoded)
	if err != nil {
		return nil, err
	}

	object, ok := copied.(map[string]any)
	if !ok {
		return nil, invalidActions("expected schema object")
	}

	return object, nil
}
func schemaForLevel(schema map[string]any, built Level) (map[string]any, error) {
	copied, err := copySchema(schema)
	if err != nil {
		return nil, err
	}

	actorIDs := make([]string, 0, len(built.Actors))
	for identifier := range built.Actors {
		actorIDs = append(actorIDs, identifier)
	}

	sort.Strings(actorIDs)
	addActorChoices(copied, actorIDs)

	return copied, nil
}
func addActorChoices(schema map[string]any, actorIDs []string) {
	if schema["type"] == "object" {
		props, _ := schema["properties"].(map[string]any)

		actor, _ := props["actor"].(map[string]any)
		if actor != nil && len(actorIDs) > 0 {
			actor["enum"] = actorIDs
		}
	}

	for _, value := range schema {
		switch child := value.(type) {
		case map[string]any:
			addActorChoices(child, actorIDs)
		case []any:
			for _, item := range child {
				if object, ok := item.(map[string]any); ok {
					addActorChoices(object, actorIDs)
				}
			}
		}
	}
}

func compileLevelSequences(source *strings.Builder, document any, catalog map[string]Declaration, built Level) error {
	source.WriteString("case " + strconv.Quote(built.Name) + ":\n switch name {\n")

	seen := map[string]bool{}
	count := 0

	object, validObject := document.(map[string]any)
	if !validObject {
		return invalidActions("expected actions document object")
	}

	sequences, validSequences := object["sequences"].([]any)
	if !validSequences {
		return invalidActions("expected sequences array")
	}

	for _, sequenceValue := range sequences {
		sequence, validSequence := sequenceValue.(map[string]any)
		if !validSequence {
			return invalidActions("expected sequence object")
		}

		name, validName := sequence["name"].(string)
		if !validName {
			return invalidActions("expected sequence name")
		}

		if seen[name] {
			return invalidActions("%s/actions.json: duplicate sequence %s", built.Directory, name)
		}

		seen[name] = true
		policy := "SequenceIgnore"

		switch sequence["onRepeat"] {
		case "restart":
			policy = "SequenceRestart"
		case "parallel":
			policy = "SequenceParallel"
		}

		stepValues, validSteps := sequence["steps"].([]any)
		if !validSteps {
			return invalidActions("expected sequence steps")
		}

		steps, err := compileSteps(stepValues, catalog, built, 1, &count, "actions.json/"+name)
		if err != nil {
			return err
		}

		source.WriteString(
			"case " + strconv.Quote(
				name,
			) + ": return (kartyEngine.Game{}).StartSequence(level,kartyEngine.Sequence{LevelName:" + strconv.Quote(
				built.Name,
			) + ",Name:" + strconv.Quote(
				built.Name+"/"+name,
			) + ",Reentry:kartyEngine." + policy + ",Steps:" + steps + "})\n",
		)
	}

	source.WriteString("}\n")

	return nil
}

func compileInvocation(source *strings.Builder, step map[string]any, declaration Declaration, level Level, location, kind string) error {
	args, validArgs := step["args"].(map[string]any)
	if !validArgs {
		return invalidActions("%s: expected action arguments", location)
	}

	call := []string{"context"}

	for argumentIndex, param := range declaration.Parameters {
		expression, err := compileArgument(source, args[param.Name], param, level, location, kind, argumentIndex)
		if err != nil {
			return err
		}

		call = append(call, expression)
	}

	source.WriteString("return " + declaration.Function + "(" + strings.Join(call, ",") + ")},")

	return nil
}

const actionValueVariants = 4

func compileStep(
	source *strings.Builder,
	value any,
	catalog map[string]Declaration,
	level Level,
	depth int,
	count *int,
	location string,
) error {
	step, validStep := value.(map[string]any)
	if !validStep {
		return invalidActions("%s: expected step object", location)
	}

	source.WriteString("{Source:" + strconv.Quote(location) + ",")

	if wait, ok := step["waitFrames"]; ok {
		frames, validFrames := wait.(json.Number)
		if !validFrames {
			return invalidActions("%s: expected wait frame count", location)
		}

		source.WriteString("Kind:kartyEngine.StepWait,WaitFrames:" + frames.String() + "},")

		return nil
	}

	kind := "action"
	if _, ok := step["condition"]; ok {
		kind = "condition"
	}

	identifier, validIdentifier := step[kind].(string)
	if !validIdentifier {
		return invalidActions("%s: expected %s identifier", location, kind)
	}

	declaration, ok := catalog[identifier]
	if !ok || declaration.Kind != kind {
		return invalidActions("%s: unknown %s", location, kind)
	}

	signature := "Run:func(context kartyEngine.ActionContext)error{"

	if kind == "condition" {
		source.WriteString("Kind:kartyEngine.StepCondition,")

		signature = "Check:func(context kartyEngine.ActionContext)(bool,error){"
	} else {
		source.WriteString("Kind:kartyEngine.StepAction,")
	}

	source.WriteString(signature)

	if err := compileInvocation(source, step, declaration, level, location, kind); err != nil {
		return err
	}

	for _, branch := range []struct{ json, goName string }{{"then", "Then"}, {"else", "Else"}, {"onFailure", "OnFailure"}} {
		if nested, ok := step[branch.json].([]any); ok {
			compiled, err := compileSteps(nested, catalog, level, depth+1, count, location+"/"+branch.json)
			if err != nil {
				return err
			}

			source.WriteString(branch.goName + ":" + compiled + ",")
		}
	}

	source.WriteString("},")

	return nil
}

func compileArgument(
	source *strings.Builder,
	value any,
	param Parameter,
	level Level,
	location, kind string,
	argumentIndex int,
) (string, error) {
	var expression string

	switch param.Type {
	case "string":
		text, valid := value.(string)
		if !valid {
			return "", invalidActions("%s: expected string argument", location)
		}

		expression = strconv.Quote(text)
	case "bool":
		boolean, valid := value.(bool)
		if !valid {
			return "", invalidActions("%s: expected boolean argument", location)
		}

		expression = strconv.FormatBool(boolean)
	case "WorldActorRef":
		actor, valid := value.(map[string]any)
		if !valid {
			return "", invalidActions("%s: expected actor argument", location)
		}

		ref, valid := actor["actor"].(string)
		if !valid {
			return "", invalidActions("%s: expected authored actor identity", location)
		}

		if !level.Actors[ref] {
			return "", invalidActions("%s: actor %q is not an authored actor in level %s", location, ref, level.Name)
		}

		expression = fmt.Sprintf("actor%d", argumentIndex)

		errReturn := "return err"
		if kind == "condition" {
			errReturn = "return false,err"
		}

		source.WriteString(expression + ",err:=context.Actor(" + strconv.Quote(ref) + ");if err!=nil{" + errReturn + "};")
	default:
		number, valid := value.(json.Number)
		if !valid {
			return "", invalidActions("%s: expected numeric argument", location)
		}

		expression = param.Type + "(" + number.String() + ")"
	}

	return expression, nil
}
