package scaffold_test

import (
	"bytes"
	"image/png"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/karty-game/karty/internal/scaffold"
	"github.com/karty-game/karty/internal/sdk"
)

func TestCreateGameWritesPinnedSDKFiles(t *testing.T) {
	t.Parallel()
	destination := filepath.Join(t.TempDir(), "pong")

	manifest, err := sdk.Resolve("0.0.1")
	if err != nil {
		t.Fatal(err)
	}

	createErr := scaffold.CreateGame(destination, "pong", manifest)
	if createErr != nil {
		t.Fatalf("CreateGame() error = %v", createErr)
	}

	for _, path := range []string{"README.md", "karty.toml", "go.mod", ".gitignore", "src/main.go", "assets/textures/player.png", ".karty/engine/game.go", ".karty/engine/components.go", ".karty/assets/textures.go"} {
		if _, statErr := os.Stat(filepath.Join(destination, path)); statErr != nil {
			t.Errorf("generated %s: %v", path, statErr)
		}
	}

	for _, path := range []string{".karty/engine/game.go", ".karty/engine/components.go", ".karty/assets/textures.go", ".karty/engine/protocol.go"} {
		generated, readErr := os.ReadFile(filepath.Join(destination, path))
		if readErr != nil {
			t.Fatal(readErr)
		}

		for _, warning := range []string{
			"// Code generated by Karty. DO NOT EDIT.",
			"// WARNING: DO NOT MODIFY THIS FILE DIRECTLY.",
			"// WARNING: MANUAL CHANGES WILL BE OVERWRITTEN.",
			"// Source of truth:",
			"// Regenerate with: karty build",
		} {
			if !strings.Contains(string(generated), warning) {
				t.Errorf("generated %s is missing header guard %q", path, warning)
			}
		}
	}

	if _, statErr := os.Stat(filepath.Join(destination, "karty.lock")); !os.IsNotExist(statErr) {
		t.Errorf("generated unexpected karty.lock: %v", statErr)
	}

	contents, err := os.ReadFile(filepath.Join(destination, "karty.toml"))
	if err != nil {
		t.Fatal(err)
	}

	if !strings.Contains(string(contents), `version = "0.0.1"`) {
		t.Errorf("karty.toml = %q, want pinned SDK version", contents)
	}

	if strings.Contains(string(contents), "[[assets.texture]]") {
		t.Errorf("karty.toml = %q, conventional texture should not need a declaration", contents)
	}

	texture, err := os.ReadFile(filepath.Join(destination, "assets", "textures", "player.png"))
	if err != nil {
		t.Fatal(err)
	}

	configuration, err := png.DecodeConfig(bytes.NewReader(texture))
	if err != nil {
		t.Fatalf("decode generated player texture: %v", err)
	}

	if configuration.Width != 32 || configuration.Height != 32 {
		t.Errorf("generated player texture dimensions = %dx%d, want 32x32", configuration.Width, configuration.Height)
	}

	mainSource, err := os.ReadFile(filepath.Join(destination, "src", "main.go"))
	if err != nil {
		t.Fatal(err)
	}

	if strings.Contains(string(mainSource), ".Move(") || !strings.Contains(string(mainSource), ".Translate(") {
		t.Errorf("generated main.go uses an unavailable movement helper: %s", mainSource)
	}

	assertTypedTextureUse(t, mainSource)
	assertExplicitRegistration(t, mainSource)

	gitignore, err := os.ReadFile(filepath.Join(destination, ".gitignore"))
	if err != nil {
		t.Fatal(err)
	}

	for _, entry := range []string{"dist/", "*_codegen.go"} {
		if !strings.Contains(string(gitignore), entry) {
			t.Errorf(".gitignore = %q, missing %q", gitignore, entry)
		}
	}
}

func assertTypedTextureUse(t *testing.T, mainSource []byte) {
	t.Helper()

	if !strings.Contains(string(mainSource), "assets.TexturePlayer") {
		t.Errorf("generated main.go does not use the typed texture reference: %s", mainSource)
	}
}

func assertExplicitRegistration(t *testing.T, mainSource []byte) {
	t.Helper()

	if !strings.Contains(string(mainSource), "//go:wasmexport karty_register\nfunc main()") {
		t.Errorf("generated main.go does not explicitly export registration: %s", mainSource)
	}
}
