// Code generated by Karty. DO NOT EDIT.
// Source: internal/build/templates/renderer-debug.js; regenerate with karty build --target web.
(() => {
  const style = document.createElement('style');
  style.textContent = `
    #karty-renderer-debug { position:fixed; bottom:max(12px,env(safe-area-inset-bottom)); left:max(12px,env(safe-area-inset-left)); z-index:10000; display:flex; gap:8px; padding:4px; background:#151b1ce8; border-radius:6px; }
    #karty-renderer-debug button, #karty-lightmap-dialog button { min-height:44px; padding:8px 14px; border:1px solid #75868a; border-radius:4px; background:#344247; color:#f1f4ef; font:14px system-ui,sans-serif; cursor:pointer; }
    #karty-renderer-debug button:disabled, #karty-lightmap-dialog button:disabled { opacity:.5; cursor:wait; }
    #karty-renderer-debug button:focus-visible, #karty-lightmap-dialog button:focus-visible { outline:3px solid #92c9ad; outline-offset:2px; }
    #karty-lightmap-dialog { width:min(1100px,calc(100vw - 24px)); max-height:calc(100dvh - 24px); padding:16px; border:1px solid #75868a; border-radius:8px; background:#151b1c; color:#edf1ea; font:14px system-ui,sans-serif; }
    #karty-lightmap-dialog::backdrop { background:#000b; }
    #karty-lightmap-dialog header { display:flex; flex-wrap:wrap; gap:8px; align-items:center; }
    #karty-lightmap-dialog h2 { font-size:18px; margin:0; flex:1; }
    #karty-lightmap-dialog .atlas-scroll { overflow:auto; max-height:calc(100dvh - 220px); background:#000; }
    #karty-lightmap-image { display:block; width:100%; height:auto; image-rendering:pixelated; }
    #karty-lightmap-image.zoomed { width:auto; max-width:none; }
    #karty-lightmap-dialog [hidden] { display:none!important; }
  `;
  document.head.append(style);
  const button = (id, text, handler) => {
    const element = document.createElement('button');
    element.id = id; element.type = 'button'; element.textContent = text;
    element.addEventListener('click', handler);
    return element;
  };
  const bar = document.createElement('nav');
  bar.id = 'karty-renderer-debug';
  bar.setAttribute('aria-label', 'Renderer debug controls');
  const dialog = document.createElement('dialog');
  dialog.id = 'karty-lightmap-dialog';
  dialog.setAttribute('aria-labelledby', 'karty-lightmap-title');
  const header = document.createElement('header');
  const title = document.createElement('h2'); title.id = 'karty-lightmap-title'; title.textContent = 'Baked lightmap';
  const status = document.createElement('p'); status.id = 'karty-lightmap-status'; status.setAttribute('role', 'status');
  const description = document.createElement('p');
  description.textContent = 'Directional atlases show RNM coefficients 0, 1 and 2, from left to right. RGBM is decoded, tone mapped and displayed as sRGB. The moving corridor light is evaluated live and is absent from this static bake.';
  const scroll = document.createElement('div'); scroll.className = 'atlas-scroll';
  const image = document.createElement('img'); image.id = 'karty-lightmap-image'; image.alt = 'Baked lightmap atlas'; image.hidden = true;
  scroll.append(image);
  let requestGeneration = 0;
  const capture = async () => {
    const generation = ++requestGeneration;
    refresh.disabled = true; zoom.disabled = true;
    image.hidden = true; image.removeAttribute('src');
    status.textContent = 'Reading the completed lightmap…';
    try {
      const snapshot = await globalThis.kartyLightmapDebug();
      if (generation !== requestGeneration || !dialog.open) return;
      if (snapshot.status !== 'ready') { status.textContent = snapshot.message; return; }
      image.src = snapshot.image;
      image.hidden = false;
      zoom.disabled = false;
      status.textContent = `${snapshot.width} × ${snapshot.height} · ${snapshot.tiles} tile${snapshot.tiles === 1 ? '' : 's'} · ${snapshot.charts} charts · ${snapshot.lights} baked lights · ${snapshot.indirect ? 'Direct + bounced lighting' : 'Direct lighting'} · ${snapshot.encoding}`;
    } catch (error) {
      if (generation === requestGeneration && dialog.open) status.textContent = String(error.message || error);
    } finally {
      if (generation === requestGeneration) refresh.disabled = false;
    }
  };
  const refresh = button('karty-lightmap-refresh', 'Refresh', capture);
  const zoom = button('karty-lightmap-zoom', '1:1 pixels', () => {
    image.classList.toggle('zoomed');
    zoom.textContent = image.classList.contains('zoomed') ? 'Fit atlas' : '1:1 pixels';
  });
  zoom.disabled = true;
  const close = button('karty-lightmap-close', 'Close', () => dialog.close());
  header.append(title, refresh, zoom, close);
  dialog.append(header, status, description, scroll);
  dialog.addEventListener('close', () => {
    requestGeneration++;
    image.hidden = true;
    image.removeAttribute('src');
    refresh.disabled = false;
  });
  const lightmap = button('karty-lightmap-open', 'Lightmap', () => {
    dialog.showModal();
    void capture();
  });
  const updateAA = mode => {
    const enabled = mode !== 'off';
    aa.textContent = `AA: ${enabled ? 'On' : 'Off'}`;
    aa.setAttribute('aria-pressed', String(enabled));
  };
  const aa = button('karty-aa-toggle', 'AA: loading', () => {
    const mode = globalThis.kartySMAA().mode === 'off' ? 'smaa' : 'off';
    updateAA(globalThis.kartySMAA(mode).mode);
  });
  aa.setAttribute('aria-label', 'Toggle anti-aliasing');
  lightmap.disabled = aa.disabled = true;
  bar.append(lightmap, aa);
  // Keep browser controls and dialog keyboard actions out of guest input.
  for (const element of [bar, dialog]) {
    for (const event of ['pointerdown', 'pointerup', 'mousedown', 'mouseup', 'touchstart', 'touchend', 'keydown', 'keyup']) {
      element.addEventListener(event, input => input.stopPropagation());
    }
  }
  document.body.append(bar, dialog);
  const ready = () => {
    if (document.documentElement.dataset.kartyState === 'error') {
      aa.textContent = 'AA unavailable';
      return;
    }
    if (document.documentElement.dataset.kartyState !== 'running') {
      setTimeout(ready, 200);
      return;
    }
    lightmap.disabled = typeof globalThis.kartyLightmapDebug !== 'function';
    aa.disabled = typeof globalThis.kartySMAA !== 'function';
    if (lightmap.disabled) lightmap.title = 'Rebuild the candidate host to enable lightmap diagnostics.';
    if (aa.disabled) aa.textContent = 'AA unavailable';
    else updateAA(globalThis.kartySMAA().mode);
  };
  ready();
})();
